### ISSUE TITLE
resolver not used for initial `SchemaFactory.newSchema(URL)` resource

### ISSUE THREAD

**Issue by liblit** [xmlresolver/xmlresolver#179] opened 2024-03-16 00:30 UTC
I am validating an HTML document against the XHTML 1.1 XML schema. All necessary resources are already downloaded and available via XML catalogs. My `XMLResolver` instance knows about these catalogs, and uses them correctly if asked to resolve a URL directly. **However, when that same URL is passed to `SchemaFactor.newSchema(URL)`, my `XMLResolver` instance is not used.**

My Kotlin test code is as follows:

```kotlin
import java.net.URI
import javax.xml.transform.stream.StreamSource
import javax.xml.validation.SchemaFactory
import org.xmlresolver.XMLResolver

fun main() {

  val resolver = XMLResolver()
  val schemaUrlString = "http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd"

  val response = resolver.resolve(resolver.getRequest(schemaUrlString))
  require(response.isResolved)
  require(response.resolvedURI.scheme == "file")

  val lsResourceResolver = resolver.lsResourceResolver
  SchemaFactory.newDefaultInstance()
      .apply { resourceResolver = lsResourceResolver }
      .newSchema(URI(schemaUrlString).toURL())
      .newValidator()
      .apply { resourceResolver = lsResourceResolver }
      .validate(StreamSource(object {}.javaClass.getResourceAsStream("/page.html")))
}
```

The two `require` checks succeed, demonstrating that the `https://…` URL was correctly resolved to a local file, thanks to my catalog of pre-downloaded resources.

The chain of validation operations that follow also succeeds…if I am online. If I disable my network connection, then the `newSchema` call fails after DNS resolution fails for `www.w3.org`:

```plain
Exception in thread "main" org.xml.sax.SAXParseException; schema_reference.4: Failed to read schema document ’http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd’, because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:306)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4258)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4241)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument1(XSDHandler.java:2532)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2239)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:589)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:618)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:577)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:543)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:281)
	at java.xml/javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:612)
	at java.xml/javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:644)
	at MainKt.main(Main.kt:18)
	at MainKt.main(Main.kt)
Caused by: java.net.UnknownHostException: www.w3.org
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/java.net.Socket.connect(Socket.java:686)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1304)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1052)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:678)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:593)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:696)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse(SchemaDOMParser.java:530)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2227)
	... 9 more
```

If I set a breakpoint in `XMLResolver.resolve(ResourceRequest)`, then the sequence of calls to that method is interesting:

1. The first call to `XMLResolver.resolve(ResourceRequest)` is directly from the `resolver.resolve` call in my test code above.  The request’s `uri` is `http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd` and the request’s `baseURI` is `null`.

1. If I am offline, then the network failure occurs before the next `XMLResolver.resolve(ResourceRequest)` call.

1. Otherwise, if I am online, then the next call to `XMLResolver.resolve(ResourceRequest)` is from deep within `com.sun.org.apache.xerces` library code.  This request’s `uri` is `http://www.w3.org/2001/xml.xsd`, and its `baseURI` is `http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd`.

1. In the next such call, the request’s `uri` is `xhtml11-model-1.xsd` and the `baseURI` is `http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd`.

1. In the next such call, the request’s `uri` is `xhtml-datatypes-1.xsd` and the `baseURI` is `file:/home/liblit/Documents/src/xml-resolver-offline/build/resources/main/org/xmlresolver/www.w3.org/MarkUp/SCHEMA/xhtml11-model-1.xsd`.  That base URI corresponds to `xhtml11-model-1.xsd` as found in my pre-downloaded catalog.

**Observe that my call to `SchemaFactory.newSchema(URI("http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd").toURL())` never results in a call to `XMLResolver.resolve(ResourceRequest)` whose `uri` is `http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd`.**  It is clear that `XMLResolver.resolve(ResourceRequest)` is being used to resolve other resources that the `xhtml11.xsd` schema requires, but it does not appear to be used for the initial `xhtml11.xsd` schema itself.  I expected that my `XMLResolver` instance would be used for that initial URL too, given that I installed it as the `SchemaFactory`’s `LSResourceResolver` instance before calling `newSchema(URL)`.

**Is there something else I should do when configuring the `SchemaFactory` to ensure that it uses my `XMLResolver` instance for _all_ resources, including the `URL` initially passed to `newSchema(URL)`?**

---

I can port the above test code to Java if you prefer that over Kotlin.  I can also make the entire test, including my catalog of XHTML schema resources, available to you as a GitHub project.

**Comment by liblit** [comment] 2024-03-16 02:36
This behavior is probably not an `XMLResolver` bug _per se_: if the `SchemaFactory` chooses not to call the resolver, that’s not something the resolver caused or can correct.

That being said, this project’s maintainers know these APIs far better than I do. Perhaps one of you can recommend a workaround. **Is there a good strategy for calling into the resolver directly, then using that result to set the schema?** The subtle part would probably be how to ensure correct resolution of any _relative_ resources used by the initial schema resource.

Thank you for any advice!

**Comment by ndw** [comment] 2024-08-05 14:35
I believe your analysis is correct. The `SchemaFactory` doesn't attempt to use the resolver for the initial URI, so there's nothing the resolver can do to resolve it locally.

If you've downloaded the schema and all of it's ancillary files and stored them in the same relative locations as they appear on the server, then you should be able to call the resolver by hand to lookup the local URI and then pass that to the `SchemaFactory`.

Internally, the resolver has the mechanisms necessary to lie. It uses them to avoid passing `classpath:` and other non-standard URI schemes back to the caller if necessary. But that's not exposed. I suppose it might be possible to do so, but just having all of the relative resources in the same relative locations on your local filesystem seems a lot cleaner.

I'm going to close this as "not a bug" but if you need more help or advice, don't hesitate to re-open it or open another one. 

Good luck!

**Closed by ndw** 2024-08-05 14:35 UTC
